"""Added Missing trusted member field

Revision ID: 5f5bcf12229d
Revises: f1a2b3c4d5e6
Create Date: 2026-03-09 18:32:21.043109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f5bcf12229d'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('jury_members', sa.Text(), nullable=True),
    sa.Column('organizers', sa.Text(), nullable=True),
    sa.Column('min_byte_count', sa.Integer(), nullable=False),
    sa.Column('min_reference_count', sa.Integer(), nullable=False),
    sa.Column('categories', sa.Text(), nullable=False),
    sa.Column('template_link', sa.Text(), nullable=True),
    sa.Column('scoring_parameters', sa.Text(), nullable=True),
    sa.Column('allowed_submission_type', sa.String(length=20), nullable=False),
    sa.Column('marks_setting_accepted', sa.Integer(), nullable=False),
    sa.Column('marks_setting_rejected', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.alter_column('contest_reports', 'status',
    #            existing_type=mysql.VARCHAR(length=20),
    #            server_default=None,
    #            existing_nullable=False)
    # op.drop_index(op.f('idx_contest_reports_contest_id'), table_name='contest_reports')
    # op.drop_index(op.f('idx_contest_reports_generated_by'), table_name='contest_reports')
    # op.drop_index(op.f('idx_contest_reports_status'), table_name='contest_reports')
    # op.drop_constraint(op.f('contest_reports_ibfk_1'), 'contest_reports', type_='foreignkey')
    # op.drop_constraint(op.f('contest_reports_ibfk_2'), 'contest_reports', type_='foreignkey')
    # op.create_foreign_key(None, 'contest_reports', 'contests', ['contest_id'], ['id'])
    # op.create_foreign_key(None, 'contest_reports', 'users', ['generated_by'], ['id'])
    # op.drop_column('contest_reports', 'updated_at')
    # op.drop_column('contest_reports', 'created_at')
    op.alter_column('users', 'is_trusted_member',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'trusted_member_request',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.drop_column('users', 'trusted_member')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trusted_member', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.alter_column('users', 'trusted_member_request',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('users', 'is_trusted_member',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.add_column('contest_reports', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('contest_reports', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.drop_constraint(None, 'contest_reports', type_='foreignkey')
    op.drop_constraint(None, 'contest_reports', type_='foreignkey')
    op.create_foreign_key(op.f('contest_reports_ibfk_2'), 'contest_reports', 'users', ['generated_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('contest_reports_ibfk_1'), 'contest_reports', 'contests', ['contest_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_contest_reports_status'), 'contest_reports', ['status'], unique=False)
    op.create_index(op.f('idx_contest_reports_generated_by'), 'contest_reports', ['generated_by'], unique=False)
    op.create_index(op.f('idx_contest_reports_contest_id'), 'contest_reports', ['contest_id'], unique=False)
    op.alter_column('contest_reports', 'status',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'pending'"),
               existing_nullable=False)
    op.drop_table('contest_requests')
    # ### end Alembic commands ###

