"""Add trusted_member field to users table

Revision ID: 87b208812990
Revises: ea8b4c071516
Create Date: 2026-01-16 18:28:57.235313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b208812990'
down_revision = 'ea8b4c071516'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add trusted_member column with default False for existing users
    # Existing users will not be trusted members by default
    # Check if column exists before adding to handle partial migration scenarios
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'trusted_member' not in columns:
        op.add_column('users', sa.Column('trusted_member', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trusted_member')
    # ### end Alembic commands ###

