"""Add categories_added and category_error columns to submissions table

Revision ID: 8ecb36347b53
Revises: 5390fc3ff139
Create Date: 2026-01-14 03:11:32.421570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ecb36347b53'
down_revision = '5390fc3ff139'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('categories_added', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('category_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'category_error')
    op.drop_column('submissions', 'categories_added')
    # ### end Alembic commands ###

