"""Check for model changes

Revision ID: 9ce4fca210b6
Revises: 30c4f4dbcb85
Create Date: 2026-01-13 20:39:43.150557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ce4fca210b6'
down_revision = '30c4f4dbcb85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Change scoring_parameters from JSON to Text (to match model definition)
    # Keep the comment as it provides useful documentation
    op.alter_column('contests', 'scoring_parameters',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               comment='Weights for scoring parameters',
               existing_comment='Weights for scoring parameters',
               existing_nullable=True)
    # Keep server default and comment for min_reference_count
    op.alter_column('contests', 'min_reference_count',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               comment='Minimum number of references required for article submissions',
               existing_comment='Minimum number of references required for article submissions',
               existing_nullable=False)
    # Keep comment for organizers
    op.alter_column('contests', 'organizers',
               existing_type=mysql.TEXT(),
               comment='Comma-separated list of organizer usernames',
               existing_comment='Comma-separated list of organizer usernames',
               existing_nullable=True)
    # Change parameter_scores from JSON to Text (to match model definition)
    # Keep the comment as it provides useful documentation
    op.alter_column('submissions', 'parameter_scores',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               comment='Per-parameter jury scores and comments',
               existing_comment='Per-parameter jury scores and comments',
               existing_nullable=True)
    # Drop index that was detected as removed from model
    op.drop_index(op.f('idx_user_contest_submission'), table_name='submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate index that was dropped in upgrade
    op.create_index(op.f('idx_user_contest_submission'), 'submissions', ['user_id', 'contest_id'], unique=False)
    # Revert parameter_scores back to JSON type
    op.alter_column('submissions', 'parameter_scores',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               comment='Per-parameter jury scores and comments',
               existing_nullable=True)
    # Revert organizers (no change needed, just keeping comment)
    op.alter_column('contests', 'organizers',
               existing_type=mysql.TEXT(),
               comment='Comma-separated list of organizer usernames',
               existing_nullable=True)
    # Revert min_reference_count (keep default and comment)
    op.alter_column('contests', 'min_reference_count',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               comment='Minimum number of references required for article submissions',
               existing_nullable=False)
    # Revert scoring_parameters back to JSON type
    op.alter_column('contests', 'scoring_parameters',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               comment='Weights for scoring parameters',
               existing_nullable=True)
    # ### end Alembic commands ###

