"""Add trusted_member_request_status field to users table

Revision ID: a28bebdbdc41
Revises: d55c876a1323
Create Date: 2026-03-09 21:44:05.513880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a28bebdbdc41'
down_revision = 'd55c876a1323'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('jury_members', sa.Text(), nullable=True),
    sa.Column('organizers', sa.Text(), nullable=True),
    sa.Column('min_byte_count', sa.Integer(), nullable=False),
    sa.Column('min_reference_count', sa.Integer(), nullable=False),
    sa.Column('categories', sa.Text(), nullable=False),
    sa.Column('template_link', sa.Text(), nullable=True),
    sa.Column('scoring_parameters', sa.Text(), nullable=True),
    sa.Column('allowed_submission_type', sa.String(length=20), nullable=False),
    sa.Column('marks_setting_accepted', sa.Integer(), nullable=False),
    sa.Column('marks_setting_rejected', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('trusted_member_request_status', sa.Enum('pending', 'approved', 'rejected', name='trusted_member_request_status_enum'), nullable=True))
    op.alter_column('users', 'is_trusted_member',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'trusted_member_request',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.drop_column('users', 'trusted_member')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trusted_member', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.alter_column('users', 'trusted_member_request',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('users', 'is_trusted_member',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.drop_column('users', 'trusted_member_request_status')
    op.drop_table('contest_requests')
    # ### end Alembic commands ###

