"""Add OAuth token columns to users table

Revision ID: a4501b0bf048
Revises: 537a7ac92f55
Create Date: 2025-12-30 12:38:34.459575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4501b0bf048'
down_revision = '537a7ac92f55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('oauth_token_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_token_secret')
    op.drop_column('users', 'oauth_token')
    # ### end Alembic commands ###

