"""Add template_link column to contests table and Add OAuth token columns to users table and Add template_added column to submissions table

Revision ID: c4d1d7879989
Revises: 9ce4fca210b6
Create Date: 2026-01-14 11:35:19.063984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d1d7879989'
down_revision = '9ce4fca210b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('oauth_token_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_token_secret')
    op.drop_column('users', 'oauth_token')
    # ### end Alembic commands ###

