"""add refrence count

Revision ID: ea8b4c071516
Revises: ed3dabd7833f
Create Date: 2026-01-14 17:20:16.404915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8b4c071516'
down_revision = 'ed3dabd7833f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

