"""allow_multiple_submissions_per_contest_but_prevent_duplicate_articles

Revision ID: eb62079dd965
Revises: 4ef9d3c7655c
Create Date: 2025-12-26 13:18:59.420638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb62079dd965'
down_revision = '4ef9d3c7655c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, convert VARCHAR ISO datetime strings to proper DATETIME format
    # Handle both formats: '2025-12-26T07:40:42Z' and '2025-12-26T07:40:42'
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE submissions 
        SET article_created_at = CASE
            WHEN article_created_at IS NULL THEN NULL
            WHEN article_created_at LIKE '%Z' THEN 
                STR_TO_DATE(REPLACE(article_created_at, 'Z', ''), '%Y-%m-%dT%H:%i:%s')
            WHEN article_created_at LIKE '%T%' THEN 
                STR_TO_DATE(article_created_at, '%Y-%m-%dT%H:%i:%s')
            ELSE NULL
        END
        WHERE article_created_at IS NOT NULL
    """))
    
    # Now change the column type from VARCHAR to DATETIME
    op.alter_column('submissions', 'article_created_at',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
    
    # Update the unique constraint to include article_link
    # Since article_link is VARCHAR(1000) which exceeds MySQL's key length limit,
    # we'll create the constraint using a prefix of article_link (first 500 chars should be enough)
    conn = op.get_bind()
    
    # Check if the old constraint exists and drop it
    result = conn.execute(sa.text("""
        SELECT CONSTRAINT_NAME 
        FROM information_schema.TABLE_CONSTRAINTS 
        WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'submissions' 
        AND CONSTRAINT_NAME = 'unique_user_contest_submission'
    """))
    
    if result.fetchone():
        # Create a non-unique index to replace the unique one (for FK optimization)
        conn.execute(sa.text("""
            CREATE INDEX idx_user_contest_submission 
            ON submissions (user_id, contest_id)
        """))
        
        # Now drop the unique constraint (the non-unique index will serve for FK lookups)
        conn.execute(sa.text("ALTER TABLE submissions DROP INDEX unique_user_contest_submission"))
    
    # Create the new unique index using a prefix of article_link
    # MySQL doesn't support prefix in UNIQUE constraints, but supports it in unique indexes
    # Using 500 characters should be enough to uniquely identify URLs
    conn.execute(sa.text("""
        CREATE UNIQUE INDEX unique_user_contest_article_submission 
        ON submissions (user_id, contest_id, article_link(500))
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore the old unique constraint
    conn = op.get_bind()
    # Drop the unique index
    conn.execute(sa.text("DROP INDEX unique_user_contest_article_submission ON submissions"))
    # Drop the non-unique index if it exists
    try:
        conn.execute(sa.text("DROP INDEX idx_user_contest_submission ON submissions"))
    except Exception:
        pass
    # Restore the old unique constraint
    op.create_index(op.f('unique_user_contest_submission'), 'submissions', ['user_id', 'contest_id'], unique=True)
    
    # Convert DATETIME back to VARCHAR ISO format string
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE submissions 
        SET article_created_at = CASE
            WHEN article_created_at IS NULL THEN NULL
            ELSE CONCAT(DATE_FORMAT(article_created_at, '%Y-%m-%dT%H:%i:%s'), 'Z')
        END
        WHERE article_created_at IS NOT NULL
    """))
    
    # Change column type back to VARCHAR
    op.alter_column('submissions', 'article_created_at',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###

